# ==============================================================================
# ШАБЛОН ДОБАВЛЕНИЯ НОВОЙ ВЕРСИИ:
#
# [[versions]]
# version = ""
# status  = "supportedAndRecommended" | "supportedButNotRecommended" | "outdated" | "comingSoon" | "experimental"
#
# ==============================================================================

[[versions]]
version = "1.21.11"
status = "supportedAndRecommended"

[[versions]]
version = "1.21.10"
status = "supportedButNotRecommended"

[[versions]]
version = "1.21.9"
status = "supportedButNotRecommended"