# ==============================================================================
# ШАБЛОН ДОБАВЛЕНИЯ НОВОЙ ВЕРСИИ:
#
# [[versions]]
# version = ""
# status  = "supportedAndRecommended" | "supportedButNotRecommended" | "outdated" | "comingSoon" | "experimental"
#
# ==============================================================================

[[versions]]
version = "26.2"
status  = "supportedAndRecommended"

[[versions]]
version = "26.1.2"
status  = "supportedButNotRecommended"


[[versions]]
version = "1.21.11"
status  = "outdated"


[[versions]]
version = "1.21.10"
status  = "outdated"


[[versions]]
version = "1.21.9"
status  = "outdated"

